name: mimiRPG
version: 1.0
author: Michalas
api-version: 1.16
softdepend: [Vault, IridiumSkyblock, Shopkeepers, MythicMobs, WorldGuard, WorldEdit]
loadbefore: [Multiverse-Core]
main: me.jomi.mimiRPG.Main
